/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_ndk_hellondk_MainActivity */

#ifndef _Included_com_test_ndk_hellondk_MainActivity
#define _Included_com_test_ndk_hellondk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_ndk_hellondk_MainActivity
 * Method:    getHelloStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_ndk_hellondk_MainActivity_getHelloStringFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
